all:
	g++ -o hello_client hello_client.cpp -lusock
	g++ -o hello_server hello_server.cpp -lusock
	g++ -o http_request http_request.cpp -lusock
	g++ -o ping ping.cpp -lusock
	g++ -o udpclient udpclient.cpp -lusock
	g++ -o udpserver udpserver.cpp -lusock

clean:
	rm hello_client
	rm hello_server
	rm http_request
	rm ping
	rm udpclient
	rm udpserver
